atomtype2num167 <- function(atname,amname){
  v <- switch (amname,
               "GLY" = switch (atname,
                               "N" = 1,
                               "CA" = 2,
                               "CB" = 2,
                               "C" = 3,
                               "O" = 4,
                               0),
               "ALA" = switch (atname,
                               "N" = 5,
                               "CA" = 6,
                               "C" = 7,
                               "O" = 8,
                               "CB" = 9,
                               0),
               "VAL" = switch (atname,
                               "N" = 10,
                               "CA" = 11,
                               "C" = 12,
                               "O" = 13,
                               "CB" = 14,
                               "CG1" = 15,
                               "CG2"= 16,
                               0),
               "LEU" = switch (atname,
                               "N" = 17,
                               "CA" = 18,
                               "C" = 19,
                               "O" = 20,
                               "CB" = 21,
                               "CG" = 22,
                               "CD1" = 23,
                               "CD2" = 24,
                               0),
               "ILE" = switch (atname,
                               "N" = 25,
                               "CA" = 26,
                               "C" = 27,
                               "O" = 28,
                               "CB" = 29,
                               "CG1" = 30,
                               "CG2" = 31,
                               "CD1" = 32,
                               0),
               "MET" = switch (atname,
                               "N" = 33,
                               "CA" = 34,
                               "C" = 35,
                               "O" = 36,
                               "CB" = 37,
                               "CG" = 38,
                               "SD" = 39,
                               "CE" = 40,
                               0),
               "PRO" = switch (atname,
                               "N" = 41,
                               "CA" = 42,
                               "C" = 43,
                               "O" = 44,
                               "CB" = 45,
                               "CG" = 46,
                               "CD" = 47,
                               0),
               "HIS" = switch (atname,
                               "N" = 48,
                               "CA" = 49,
                               "C" = 50,
                               "O" = 51,
                               "CB" = 52,
                               "CG" = 53,
                               "ND1" = 54,
                               "CD2" = 55,
                               "CE1" = 56,
                               "NE2" = 57,
                               0),
               "PHE" = switch (atname,
                               "N" = 58,
                               "CA" = 59,
                               "C" = 60,
                               "O" = 61,
                               "CB" = 62,
                               "CG" = 63,
                               "CD1" = 64,
                               "CD2" = 65,
                               "CE1" = 66,
                               "CE2" = 67,
                               "CZ" = 68,
                               0),
               "TYR" = switch (atname,
                               "N" = 69,
                               "CA" = 70,
                               "C" = 71,
                               "O" = 72,
                               "CB" = 73,
                               "CG" = 74,
                               "CD1" = 75,
                               "CD2" = 76,
                               "CE1" = 77,
                               "CE2" = 78,
                               "CZ" = 79,
                               "OH" = 80,
                               0),
               "TRP" = switch (atname,
                               "N" = 81,
                               "CA" = 82,
                               "C" = 83,
                               "O" = 84,
                               "CB" = 85,
                               "CG" = 86,
                               "CD1" = 87,
                               "NE1" = 88,
                               "CD2" = 89,
                               "CE2" = 90,
                               "CE3" = 91,
                               "CZ3" = 92,
                               "CZ2" = 93,
                               "CH2" = 94,
                               0),
               "CYS" = switch (atname,
                               "N" = 95,
                               "CA" = 96,
                               "C" = 97,
                               "O" = 98,
                               "CB" = 99,
                               "SG" = 100,
                               0),
               "CYSS" = switch (atname,
                               "N" = 95,
                               "CA" = 96,
                               "C" = 97,
                               "O" = 98,
                               "CB" = 99,
                               "SG" = 100,
                               0),
               "CYH" = switch (atname,
                               "N" = 95,
                               "CA" = 96,
                               "C" = 97,
                               "O" = 98,
                               "CB" = 99,
                               "SG" = 100,
                               0),
               "SER" = switch (atname,
                               "N" = 101,
                               "CA" = 102,
                               "C" = 103,
                               "O" = 104,
                               "CB" = 105,
                               "OG" = 106,
                               0),
               "THR" = switch (atname,
                               "N" = 107,
                               "CA" = 108,
                               "C" = 109,
                               "O" = 110,
                               "CB" = 111,
                               "OG1" = 112,
                               "CG2" = 113,
                               0),
               "ASN" = switch (atname,
                               "N" = 114,
                               "CA" = 115,
                               "C" = 116,
                               "O" = 117,
                               "CB" = 118,
                               "CG" = 119,
                               "OD1" = 120,
                               "ND2" = 121,
                               0),
               "GLN" = switch (atname,
                               "N" = 122,
                               "CA" = 123,
                               "C" = 124,
                               "O" = 125,
                               "CB" = 126,
                               "CG" = 127,
                               "CD" = 128,
                               "OE1" = 129,
                               "NE2" = 130,
                               0),
               "ASP" = switch (atname,
                               "N" = 131,
                               "CA" = 132,
                               "C" = 133,
                               "O" = 134,
                               "CB" = 135,
                               "CG" = 136,
                               "OD1" = 137,
                               "OD2" = 138,
                               0),
               "GLU" = switch (atname,
                               "N" = 139,
                               "CA" = 140,
                               "C" = 141,
                               "O" = 142,
                               "CB" = 143,
                               "CG" = 144,
                               "CD" = 145,
                               "OE1" = 146,
                               "OE2" = 147,
                               0),
               "LYS" = switch (atname,
                               "N" = 148,
                               "CA" = 149,
                               "C" = 150,
                               "O" = 151,
                               "CB" = 152,
                               "CG" = 153,
                               "CD" = 154,
                               "CE" = 155,
                               "NZ" = 156,
                               0),
               "LYZ" = switch (atname,
                               "N" = 148,
                               "CA" = 149,
                               "C" = 150,
                               "O" = 151,
                               "CB" = 152,
                               "CG" = 153,
                               "CD" = 154,
                               "CE" = 155,
                               "NZ" = 156,
                               0),
               "ARG" = switch (atname,
                               "N" = 157,
                               "CA" = 158,
                               "C" = 159,
                               "O" = 160,
                               "CB" = 161,
                               "CG" = 162,
                               "CD" = 163,
                               "NE" = 164,
                               "CZ" = 165,
                               "NH1" = 166,
                               "NH2" = 167,
                               0),
               )
  v
}


