---
title: "Figure and table"
author: "peyman"
date: "2024-03-12"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Library   
```{r libraries, include=FALSE}
#library(kableExtra)
options(knitr.table.format = "latex")
library(readr)
library(data.table)
library(MASS)
library(tidyverse)
library(dplyr)
library(tidyr)
library(ggplot2)
library(ggrepel)
library(ggpubr)
library(ggpointdensity)
library(ggpubr)
library(igraph)
library(fpc)
library(grid)
library(gridExtra)
library(reshape2)
library(visNetwork)
library(pheatmap)
library(umap)
library(Rtsne)
library(viridis)
library(viridisLite)
library(bio3d)
library(caret)
library(e1071)
library(randomForest)
library(seqinr)
library(geometry)
library(ape)
library(colorspace)
library(dendextend)
library(dynamicTreeCut)
library(caret)
library(ggtree)
library(phangorn)
library(tanggle)
library(stringr)
library(protr)
library(proxy)
library(class)
library(readxl)
library(ggh4x)
library(mclust)
source('mytheme.R')
```

# Custom distance

```{r}
manhat <- function(X, Y){
  x<-X; y<-Y
  xy <- abs(x - y)
  xy <- xy[xy != 0]
  if(length(xy)==0){
    d <- 0
  }else{
    d <- sum(xy)/length(xy)
  }
  return(d)
}
```

# Figures
# Preprocess for Fig1

```{r}
# astral 95
df_seq <- readRDS("Data/rds/E210.seq_astral_95.rds") 
df_seq = df_seq[!is.na(df_seq$FL),] 

df_str <- readRDS("Data/rds/E210.astral_95.rds") 
df_str = df_str[!is.na(df_str$FL),] 
m<-match(df_str$scopeID,df_seq$scopeID)
df_str <- df_str[-which(is.na(m)),]
# **** total energy 95
df_tot95 <- data.frame(data='Astral 95', class=df_str$class,
                       length = df_seq$length,
                       seq=rowSums(df_seq[,-c(1:8)]),
                       str=rowSums(df_str[,-c(1:8)]))
# **** distance 95
dis_seq <- dist(df_seq[,-c(1:8)],method = manhat)
dis_str <- dist(df_str[,-c(1:8)],method = manhat)
idx <- sample(length(dis_str),100000)
df_dis95 <- data.frame(data='Astral 95',
                       dis_str=as.vector(dis_str)[idx],
                       dis_seq=as.vector(dis_seq)[idx])
#saveRDS(df_dis95,'manuscript/fig_data/dis_95_manhat.rds')
# ************************************************************
# astral 40
df_seq <- readRDS("Data/rds/E210.seq_astral_40.rds") 
df_seq = df_seq[!is.na(df_seq$FL),] 

df_str <- readRDS("Data/rds/E210.astral_40.rds") 
df_str = df_str[!is.na(df_str$FL),] 
m<-match(df_str$scopeID,df_seq$scopeID)
df_str <- df_str[-which(is.na(m)),]
# **** total energy 40
df_tot40 <- data.frame(data='Astral 40', class=df_str$class,
                       length=df_seq$length,
                       seq=rowSums(df_seq[,-c(1:8)]),
                       str=rowSums(df_str[,-c(1:8)]))
# **** distance 40
dis_seq <- dist(df_seq[,-c(1:8)],method = manhat)
dis_str <- dist(df_str[,-c(1:8)],method = manhat)
idx <- sample(length(dis_str),100000)
df_dis40 <- data.frame(data='Astral 40',
                       dis_str=as.vector(dis_str)[idx],
                       dis_seq=as.vector(dis_seq)[idx])
#saveRDS(df_dis40,'manuscript/fig_data/dis_40_manhat.rds')
# **************************************
df_tot <- rbind(df_tot40, df_tot95)
#saveRDS(df_tot, 'manuscript/fig_data/df_total_energy.rds')
```

## Fig1

```{r}
# ************** total energy 40 and 95
df_tot <- readRDS('manuscript/fig_data/df_total_energy.rds')
df_tot$data <- ifelse(df_tot$data=='Astral 40','ASTRAL40','ASTRAL95')
AB <- ggplot(df_tot, aes(seq/2000,str/1000))+
       geom_pointdensity(adjust = .1,alpha=.3,show.legend = T)+
       geom_smooth(method = 'glm',col='red')+
       stat_cor(method = "pearson", size=5, color = "red", geom = "label") +
       scale_color_viridis()+facet_wrap(vars(data))+
       theme_bw(base_line_size = .3)+
       xlab('Total energy (sequence)')+ylab('Total energy (structure)')+
  mytheme()
# ************** distance 40 and 95
df_dis40<-readRDS('manuscript/fig_data/dis_40_manhat.rds')
df_dis95<-readRDS('manuscript/fig_data/dis_95_manhat.rds')
df_dis <- rbind(df_dis40, df_dis95)
df_dis$data <- ifelse(df_dis$data=='Astral 40','ASTRAL40','ASTRAL95')

CD <- ggplot(df_dis, aes(dis_seq,dis_str))+
       geom_pointdensity(adjust = .1,alpha=.3,show.legend = T)+
       geom_smooth(method = 'glm',col='red')+
       stat_cor(method = "pearson", size=5, color = "red", geom = "label") +
       scale_color_viridis()+facet_wrap(vars(data))+
       theme_bw(base_line_size = .3)+
       xlab('Distance (CPE)')+ylab('Distance (SPE)')+
       mytheme()

ggarrange(NULL,
    AB, NULL,CD, ncol = 1,
    heights = c(0.09, 1, 0.17, 1),
    labels = c('',"A", "", "B"),
    font.label = list(size = 30),    # color = "red"
    hjust = -.5,vjust = 0
    )

# save FIG1.pdf 10x9
```

## Fig2

```{r}
df_tot <- readRDS('manuscript/fig_data/df_total_energy.rds')
df_tot <- df_tot[df_tot$class%in%c('a','b','c','d'),]
df_tot$class[df_tot$class=='a']<-'All_alpha'
df_tot$class[df_tot$class=='b']<-'All_beta'
df_tot$class[df_tot$class=='c']<-'alpha/beta'
df_tot$class[df_tot$class=='d']<-'alpha+beta'
df_tot$data <- ifelse(df_tot$data=='Astral 40','ASTRAL40','ASTRAL95')

AB <- ggplot(df_tot,aes(class,str/length,fill=class))+
  geom_boxplot(outlier.alpha = .01)+
  facet_wrap(vars(data))+
  xlab('')+ylab('Total energy (structure)')+
  coord_cartesian(ylim = c(-15, -4))+
  mytheme()+theme(legend.title = element_blank(),
               axis.text.x = element_blank())

CD <- ggplot(df_tot,aes(class,seq/(2*length),fill=class))+
  geom_boxplot(outlier.alpha = .1)+
  facet_wrap(vars(data))+
  xlab('')+ylab('Total energy (sequence)')+
  coord_cartesian(ylim = c(-15, -6))+
  mytheme()+theme(legend.title = element_blank(),
               axis.text.x = element_blank())


ggarrange(NULL,
    AB, NULL,CD, ncol = 1,
    heights = c(0.09, 1, 0.17, 1),
    labels = c('',"A", "", "B"),
    common.legend = T, legend = 'bottom',
    font.label = list(size = 30),    # color = "red"
    hjust = -.5,vjust = 0
    )
# save FIG2.pdf 10x9
```

## Fig3

```{r}
source('mytheme.R')
# ******** str40
df <- readRDS("Data/rds/E210.astral_40.rds")
df <- df[df$class %in% c("a","b")& df$length > 100 & !is.na(df$FF),]
df <- df[,c(5,3,9:218)]
sc <- apply(df[-c(1:2)], 2, FUN = function(x){x/sd(x)})
df[-c(1:2)] <- sc
dis <- as.matrix(proxy::dist(df[,-c(1,2)]/df$length, method = manhat))
ump <- umap(d = dis,
            n_neighbors = 30,
            min_dist = 0.1,
            input="dist")
ump_df_str40 <- data.frame(data='Astral 40',type='Structure',
                           class=df[,1],
                           UMAP1 = ump$layout[, 1],
                           UMAP2 = ump$layout[, 2])
ump_df_str40$class <- ifelse(ump_df_str40$class=='a','All-alpha','All-beta')

# ******** seq40
df <- readRDS("Data/rds/E210.seq_astral_40.rds")
df <- df[df$class %in% c("a","b")& df$length > 100 & !is.na(df$FF),]
df <- df[,c(5,3,9:218)]
sc <- apply(df[-c(1:2)], 2, FUN = function(x){x/sd(x)})
df[-c(1:2)] <- sc
dis <- as.matrix(proxy::dist(df[,-c(1,2)]/df$length, method = manhat))
ump <- umap(d = dis,
            n_neighbors = 30,
            min_dist = 0.1,
            input="dist")
ump_df_seq40 <- data.frame(data='Astral 40',type='Sequence',
                           class=df[,1],
                           UMAP1 = ump$layout[, 1],
                           UMAP2 = ump$layout[, 2])
ump_df_seq40$class <- ifelse(ump_df_seq40$class=='a','All-alpha','All-beta')

# ******** str95
df <- readRDS("Data/rds/E210.astral_95.rds")
df <- df[df$class %in% c("a","b")& df$length > 100 & !is.na(df$FF),]
df <- df[,c(5,3,9:218)]
dis <- as.matrix(proxy::dist(df[,-c(1,2)]/df$length, method = manhat))
ump <- umap(d = dis,
            n_neighbors = 30,
            min_dist = 0.1,
            input="dist")
ump_df_str95 <- data.frame(data='Astral 95',type='Structure',
                           class=df[,1],
                           UMAP1 = ump$layout[, 1],
                           UMAP2 = ump$layout[, 2])
ump_df_str95 <- ump_df_str95[ump_df_str95$UMAP1> -1.5 & ump_df_str95$UMAP1< 4.5,]
ump_df_str95 <- ump_df_str95[ump_df_str95$UMAP2> -1.5 & ump_df_str95$UMAP2< 6,]
ump_df_str95$class <- ifelse(ump_df_str95$class=='a','All-alpha','All-beta')

# ******** seq95
df <- readRDS("Data/rds/E210.seq_astral_95.rds")
df <- df[df$class %in% c("a","b")& df$length > 100 & !is.na(df$FF),]
df <- df[,c(5,3,9:218)]
dis <- as.matrix(proxy::dist(df[,-c(1,2)]/df$length, method = manhat))
ump <- umap(d = dis,
            n_neighbors = 30,
            min_dist = 0.1,
            input="dist")
ump_df_seq95 <- data.frame(data='Astral 95',type='Sequence',
                           class=df[,1],
                           UMAP1 = ump$layout[, 1],
                           UMAP2 = ump$layout[, 2])
ump_df_seq95 <- ump_df_seq95[ump_df_seq95$UMAP1> -5 & ump_df_seq95$UMAP1< 1.5,]
ump_df_seq95 <- ump_df_seq95[ump_df_seq95$UMAP2> -2.5 & ump_df_seq95$UMAP2< 3,]
ump_df_seq95$class <- ifelse(ump_df_seq95$class=='a','All-alpha','All-beta')
# **** rbind
ump_df <- rbind(ump_df_str40,ump_df_seq40,
                ump_df_str95,ump_df_seq95)

# save(ump_df_seq40,ump_df_seq95,ump_df_str40,ump_df_str95,
#      file = 'manuscript/fig_data/UMPs.RData')
load('manuscript/fig_data/UMPs.RData')
ump_df_str40$type <- ifelse(ump_df_str40$type=='Structure','SPE','CPE')
ump_df_seq40$type <- ifelse(ump_df_seq40$type=='Structure','SPE','CPE')
ump_df_str95$type <- ifelse(ump_df_str95$type=='Structure','SPE','CPE')
ump_df_seq95$type <- ifelse(ump_df_seq95$type=='Structure','SPE','CPE')

ump_df_str40$data <- ump_df_seq40$data <- 'ASTRAL40'

p1<-ggplot(ump_df_str40,aes(UMAP1, UMAP2, color= class)) +
  geom_point(alpha=.7,size=.5) + 
  #facet_grid(data ~ type)+xlab('')+ylab('')+
  mytheme()+scale_color_manual(values = c('green','magenta'))+
  theme(legend.title = element_blank(),
        legend.text = element_text(size = 18))+
  guides(color = guide_legend(override.aes = list(size = 5)))

p2<-ggplot(ump_df_seq40,aes(UMAP1, UMAP2, color= class)) +
  geom_point(alpha=.7,size=.5) + 
  facet_grid( ~ type)+xlab('')+
  #facet_grid(data ~ type)+xlab('')+ylab('')+
  mytheme()+scale_color_manual(values = c('green','magenta'))+
  theme(legend.title = element_blank(),
        legend.text = element_text(size = 18))+
  guides(color = guide_legend(override.aes = list(size = 5)))

p3<-ggplot(ump_df_str95,aes(UMAP1, UMAP2, color= class)) +
  geom_point(alpha=.7,size=.5) +
  facet_grid(rows = vars(data))+ylab('')+
  mytheme()+scale_color_manual(values = c('green','magenta'))+
  theme(legend.title = element_blank(),
        legend.text = element_text(size = 18))+
  guides(color = guide_legend(override.aes = list(size = 5)))


p4<-ggplot(ump_df_seq95,aes(UMAP1, UMAP2, color= class)) +
  geom_point(alpha=.7,size=.5) + 
  #facet_grid(rows = vars(data))+ylab('')+
  mytheme()+scale_color_manual(values = c('green','magenta'))+
  theme(legend.title = element_blank(),
        legend.text = element_text(size = 18))+
  guides(color = guide_legend(override.aes = list(size = 5)))

# ********
ggarrange(NULL,NULL,NULL,
          p2,NULL,p1,
          NULL,NULL,NULL,
          p4,NULL,p3,ncol = 3,nrow = 4,
          common.legend = T,
          labels = c('','','',
                     "A", "", "B",
                     '','','',
                     'C','','D'),
          font.label = list(size = 30),
          widths = c(1, 0.12, 1),
          heights = c(.1, 1, 0.12, 1),
          hjust = -.5,vjust = 0,legend = 'bottom')

# save FIG3.pdf 10x10
```

## Fig4A

```{r}
# ******** str40
df <- readRDS("Data/rds/E210.astral40.rds")
df <- df[df$fold%in%c('a.100','a.104'),]
df <- df[!is.na(df$FF),]
df <- df[,c(6,3,9:218)]
df$length <- as.numeric(df$length)
dis <- as.matrix(proxy::dist(df[,-1], method = manhat))
ump <- umap(d = dis,
            n_neighbors = 30,
            min_dist = 0.1,
            input="dist")
ump_df_str <- data.frame(data='Astral 40',type='SPE',
                           class=df[,1],
                           UMAP1 = ump$layout[, 1],
                           UMAP2 = ump$layout[, 2])

# ******** seq40
df <- readRDS("Data/rds/E210.seq_astral40.rds")
df <- df[df$fold%in%c('a.100','a.104'),]
df <- df[!is.na(df$FF),]
df <- df[,c(6,3,9:218)]
df$length <- as.numeric(df$length)
dis <- as.matrix(proxy::dist(df[,-1], method = manhat))
ump <- umap(d = dis,
            n_neighbors = 30,
            min_dist = 0.1,
            input="dist")
ump_df_seq <- data.frame(data='Astral 40',type='CPE',
                           class=df[,1],
                           UMAP1 = ump$layout[, 1],
                           UMAP2 = ump$layout[, 2])
z <- rbind(ump_df_str,ump_df_seq)
z$data <- 'ASTRAL40'
z$class <- ifelse(z$class=='a.100', 'a.100    ','a.104')

p1 <- ggplot(z,aes(UMAP1, UMAP2, color= class)) +
    geom_point(alpha=.7) + 
    facet_nested(~ data+type,independent = T,scales = T)+
  ylab('')+xlab('')+
  mytheme()+
  theme(axis.text.y = element_blank(),
        axis.text.x = element_blank(),
        legend.title = element_blank(),
        legend.text = element_text(size = 18))+
  guides(color = guide_legend(override.aes = list(size = 3)))
# ---------------------
# ******** str95
df <- readRDS("Data/rds/E210.astral_95.rds")
df <- df[df$fold%in%c('a.100','a.104'),]
df <- df[!is.na(df$FF),]
df <- df[,c(6,3,9:218)]
df$length <- as.numeric(df$length)
dis <- as.matrix(proxy::dist(df[,-1], method = manhat))
ump <- umap(d = dis,
            n_neighbors = 30,
            min_dist = 0.1,
            input="dist")
ump_df_str <- data.frame(data='Astral 95',type='SPE',
                           class=df[,1],
                           UMAP1 = ump$layout[, 1],
                           UMAP2 = ump$layout[, 2])

# ******** seq95
df <- readRDS("Data/rds/E210.seq_astral_95.rds")
df <- df[df$fold%in%c('a.100','a.104'),]
df <- df[!is.na(df$FF),]
df <- df[,c(6,3,9:218)]
df$length <- as.numeric(df$length)
dis <- as.matrix(proxy::dist(df[,-1], method = manhat))
ump <- umap(d = dis,
            n_neighbors = 30,
            min_dist = 0.1,
            input="dist")
ump_df_seq <- data.frame(data='Astral 95',type='CPE',
                           class=df[,1],
                           UMAP1 = ump$layout[, 1],
                           UMAP2 = ump$layout[, 2])
z <- rbind(ump_df_str,ump_df_seq)
z$data <- 'ASTRAL95'
z$class <- ifelse(z$class=='a.100', 'a.100    ','a.104')


p2 <- ggplot(z,aes(UMAP1, UMAP2, color= class)) +
    geom_point(alpha=.7) + 
    facet_nested(~ data+type,independent = T,scales = T)+
  ylab('')+xlab('')+
  mytheme()+
  theme(axis.text.y = element_blank(),
        axis.text.x = element_blank(),
        legend.title = element_blank(),
        legend.text = element_text(size = 18))+
  guides(color = guide_legend(override.aes = list(size = 3)))

A<-ggarrange(NULL,NULL,NULL,NULL,
             NULL,p1,NULL,p2,nrow = 2,ncol = 4,
          common.legend = T,legend = 'right',
          widths = c(.1,1, 0.0, 1),
          heights = c(.07,1),
          labels = c('','','','',
                     '',"A", "", ""),
  font.label = list(size = 30),
  hjust = .2,vjust = 0)

```

## Fig4B

```{r}
# ******** str40
df <- readRDS("Data/rds/E210.astral40.rds")
df <- df[df$superfamily%in%c('a.29.2','a.29.3'),]
df <- df[!is.na(df$FF),]
df <- df[,c(7,3,9:218)]
df$length <- as.numeric(df$length)
dis <- as.matrix(proxy::dist(df[,-1], method = manhat))
ump <- umap(d = dis,
            n_neighbors = 30,
            min_dist = 0.1,
            input="dist")
ump_df_str <- data.frame(data='Astral 40',type='SPE',
                           class=df[,1],
                           UMAP1 = ump$layout[, 1],
                           UMAP2 = ump$layout[, 2])

# ******** seq40
df <- readRDS("Data/rds/E210.seq_astral40.rds")
df <- df[df$superfamily%in%c('a.29.2','a.29.3'),]
df <- df[!is.na(df$FF),]
df <- df[,c(7,3,9:218)]
df$length <- as.numeric(df$length)
dis <- as.matrix(proxy::dist(df[,-1], method = manhat))
ump <- umap(d = dis,
            n_neighbors = 30,
            min_dist = 0.1,
            input="dist")
ump_df_seq <- data.frame(data='Astral 40',type='CPE',
                           class=df[,1],
                           UMAP1 = ump$layout[, 1],
                           UMAP2 = ump$layout[, 2])
z <- rbind(ump_df_str,ump_df_seq)
z$data <- 'ASTRAL40'
z$class <- ifelse(z$class=='a.29.2', 'a.29.2   ','a.29.3')

p1 <- ggplot(z,aes(UMAP1, UMAP2, color= class)) +
    geom_point(alpha=.7) + 
    facet_nested(~ data+type,independent = T,scales = T)+
  ylab('')+xlab('')+
  mytheme()+
  theme(axis.text.y = element_blank(),
        axis.text.x = element_blank(),
        legend.title = element_blank(),
        legend.text = element_text(size = 18))+
  guides(color = guide_legend(override.aes = list(size = 3)))
# ---------------------
# ******** str95
df <- readRDS("Data/rds/E210.astral_95.rds")
df <- df[df$superfamily%in%c('a.29.2','a.29.3'),]
df <- df[!is.na(df$FF),]
df <- df[,c(7,3,9:218)]
df$length <- as.numeric(df$length)
dis <- as.matrix(proxy::dist(df[,-1], method = manhat))
ump <- umap(d = dis,
            n_neighbors = 30,
            min_dist = 0.1,
            input="dist")
ump_df_str <- data.frame(data='Astral 95',type='SPE',
                           class=df[,1],
                           UMAP1 = ump$layout[, 1],
                           UMAP2 = ump$layout[, 2])

# ******** seq95
df <- readRDS("Data/rds/E210.seq_astral_95.rds")
df <- df[df$superfamily%in%c('a.29.2','a.29.3'),]
df <- df[!is.na(df$FF),]
df <- df[,c(7,3,9:218)]
df$length <- as.numeric(df$length)
dis <- as.matrix(proxy::dist(df[,-1], method = manhat))
ump <- umap(d = dis,
            n_neighbors = 30,
            min_dist = 0.1,
            input="dist")
ump_df_seq <- data.frame(data='Astral 95',type='CPE',
                           class=df[,1],
                           UMAP1 = ump$layout[, 1],
                           UMAP2 = ump$layout[, 2])
z <- rbind(ump_df_str,ump_df_seq)
z$data <- 'ASTRAL95'
z$class <- ifelse(z$class=='a.29.2', 'a.29.2   ','a.29.3')

p2 <- ggplot(z,aes(UMAP1, UMAP2, color= class)) +
    geom_point(alpha=.7) + 
    facet_nested(~ data+type,independent = T,scales = T)+
  ylab('')+xlab('')+
  mytheme()+
  theme(axis.text.y = element_blank(),
        axis.text.x = element_blank(),
        legend.title = element_blank(),
        legend.text = element_text(size = 18))+
  guides(color = guide_legend(override.aes = list(size = 3)))

B <- ggarrange(NULL,NULL,NULL,NULL,
             NULL,p1,NULL,p2,nrow = 2,ncol = 4,
          common.legend = T,legend = 'right',
          widths = c(.1,1, 0.0, 1),
          heights = c(.07,1),
          labels = c('','','','',
                     '',"B", "", ""),
  font.label = list(size = 30),
  hjust = .2,vjust = 0)
```

## Fig4C

```{r}
# ******** str40
df <- readRDS("Data/rds/E210.astral40.rds")
df <- df[df$family%in%c('a.25.1.0','a.25.1.2'),]
df <- df[!is.na(df$FF),]
df <- df[,c(8,3,9:218)]
df$length <- as.numeric(df$length)
dis <- as.matrix(proxy::dist(df[,-1], method = manhat))
ump <- umap(d = dis,
            n_neighbors = 10,
            min_dist = 0.1,
            input="dist")
ump_df_str <- data.frame(data='Astral 40',type='SPE',
                           class=df[,1],
                           UMAP1 = ump$layout[, 1],
                           UMAP2 = ump$layout[, 2])

# ******** seq40
df <- readRDS("Data/rds/E210.seq_astral40.rds")
df <- df[df$family%in%c('a.25.1.0','a.25.1.2'),]
df <- df[!is.na(df$FF),]
df <- df[,c(8,3,9:218)]
df$length <- as.numeric(df$length)
dis <- as.matrix(proxy::dist(df[,-1], method = manhat))
ump <- umap(d = dis,
            n_neighbors = 10,
            min_dist = 0.1,
            input="dist")
ump_df_seq <- data.frame(data='Astral 40',type='CPE',
                           class=df[,1],
                           UMAP1 = ump$layout[, 1],
                           UMAP2 = ump$layout[, 2])
z <- rbind(ump_df_str,ump_df_seq)
z$data <- 'ASTRAl40'

p1 <- ggplot(z,aes(UMAP1, UMAP2, color= class)) +
    geom_point(alpha=.7) + 
    facet_nested(~ data+type,independent = T,scales = T)+
  ylab('')+xlab('')+
  mytheme()+
  theme(axis.text.y = element_blank(),
        axis.text.x = element_blank(),
        legend.title = element_blank(),
        legend.text = element_text(size = 18))+
  guides(color = guide_legend(override.aes = list(size = 3)))
# ---------------------
# ******** str95
df <- readRDS("Data/rds/E210.astral_95.rds")
df <- df[df$family%in%c('a.25.1.0','a.25.1.2'),]
df <- df[!is.na(df$FF),]
df <- df[,c(8,3,9:218)]
df$length <- as.numeric(df$length)
dis <- as.matrix(proxy::dist(df[,-1], method = manhat))
ump <- umap(d = dis,
            n_neighbors = 10,
            min_dist = 0.1,
            input="dist")
ump_df_str <- data.frame(data='Astral 95',type='SPE',
                           class=df[,1],
                           UMAP1 = ump$layout[, 1],
                           UMAP2 = ump$layout[, 2])

# ******** seq95
df <- readRDS("Data/rds/E210.seq_astral_95.rds")
df <- df[df$family%in%c('a.25.1.0','a.25.1.2'),]
df <- df[!is.na(df$FF),]
df <- df[,c(8,3,9:218)]
df$length <- as.numeric(df$length)
dis <- as.matrix(proxy::dist(df[,-1], method = manhat))
ump <- umap(d = dis,
            n_neighbors = 10,
            min_dist = 0.1,
            input="dist")
ump_df_seq <- data.frame(data='Astral 95',type='CPE',
                           class=df[,1],
                           UMAP1 = ump$layout[, 1],
                           UMAP2 = ump$layout[, 2])
z <- rbind(ump_df_str,ump_df_seq)
z$data <- 'ASTRAL95'

p2 <- ggplot(z,aes(UMAP1, UMAP2, color= class)) +
    geom_point(alpha=.7) + 
    facet_nested(~ data+type,independent = T,scales = T)+
  ylab('')+xlab('')+
  mytheme()+
  theme(axis.text.y = element_blank(),
        axis.text.x = element_blank(),
        legend.title = element_blank(),
        legend.text = element_text(size = 18))+
  guides(color = guide_legend(override.aes = list(size = 3)))

C <- ggarrange(NULL,NULL,NULL,NULL,
             NULL,p1,NULL,p2,nrow = 2,ncol = 4,
          common.legend = T,legend = 'right',
          widths = c(.1,1, 0.0, 1),
          heights = c(.07,1),
          labels = c('','','','',
                     '',"C", "", ""),
  font.label = list(size = 30),
  hjust = .2,vjust = 0)
```

##Fig4ABC

```{r}
ggarrange(NULL,A,B,C,ncol = 1,
          heights = c(0.07,1,1,1))
# save FIG4.pdf 10x10
```

## Fig5EF

```{r}
# ******** a.29.3
# ****** structure40
df <- readRDS("Data/rds/E210.astral40.rds") 
df = df[!is.na(df$FL),] 
idx<- df$superfamily%in% 'a.29.3'
dis <- as.matrix(dist(df[idx,-c(1:8)],method = manhat))
dis <- data.frame(gr=df$family[idx], dis)
fa<-unique(dis$gr)

between<-c() 
within<-c()
for (i in 1:length(fa)) {  
  print(i)   
  x <- fa[i]  
  idx <- which(dis$gr==x)
  y <- dis[idx,(idx+1)]
  within <- c(within, y[lower.tri(y)])
  x <- dis[idx,-c(1,idx+1)]   
  x <- as.vector(as.matrix(x))  
  x <- x[!is.na(x)]   
  between<-c(between,x) 
}
df_family_str <- data.frame(data='ASTRAL40-superfamily a.29.3',type='SPE',
                            gr=rep(c('within','between'),
                                   c(length(within),length(between))),
                            distance=c(within,between)) 
# ****** sequence40
df <- readRDS("Data/rds/E210.seq_astral40.rds") 
df = df[!is.na(df$FL),] 
idx<- df$superfamily%in% 'a.29.3'
dis <- as.matrix(dist(df[idx,-c(1:8)],method = manhat))
dis <- data.frame(gr=df$family[idx], dis)
fa<-unique(dis$gr)

between<-c() 
within<-c()
for (i in 1:length(fa)) {  
  print(i)   
  x <- fa[i]  
  idx <- which(dis$gr==x)
  y <- dis[idx,(idx+1)]
  within <- c(within, y[lower.tri(y)])
  x <- dis[idx,-c(1,idx+1)]   
  x <- as.vector(as.matrix(x))  
  x <- x[!is.na(x)]   
  between<-c(between,x) 
}
df_family_seq <- data.frame(data='ASTRAL40-superfamily a.29.3',type='CPE',
                            gr=rep(c('within','between'),
                                   c(length(within),length(between))),
                            distance=c(within,between)) 
# **********
df_family <- rbind(df_family_seq, df_family_str)

E <- ggboxplot(df_family, x='gr',y='distance', 
          fill = 'gr',alpha=.5,outlier.shape = NA)+
  stat_summary(fun.y=mean, geom="point", shape=8,
               size=2, color="red", fill="red")+xlab('')+
  mytheme()+
  theme(legend.position = 'none',
        axis.text.x = element_blank())+
  scale_fill_viridis(discrete = TRUE, alpha=0.6)+
  stat_compare_means(method = 't.test',size=3,label.y = 18,
                     label.x = 1.4,
                     aes(label = paste0("p = ", ..p.format..)))+
  facet_nested(~ data + type)+
  coord_cartesian(ylim = c(0, 20))
mylegend <- get_legend(E+
                       theme(legend.position = 'bottom',
                             legend.title = element_blank(),
                             legend.text = element_text(size = 20)))
# ******************************************
# ****** structure95
df <- readRDS("Data/rds/E210.astral_95.rds") 
df = df[!is.na(df$FL),] 
idx<- df$superfamily%in% 'a.29.3'
dis <- as.matrix(dist(df[idx,-c(1:8)],method = manhat))
dis <- data.frame(gr=df$family[idx], dis)
fa<-unique(dis$gr)

between<-c() 
within<-c()
for (i in 1:length(fa)) {  
  print(i)   
  x <- fa[i]  
  idx <- which(dis$gr==x)
  y <- dis[idx,(idx+1)]
  within <- c(within, y[lower.tri(y)])
  x <- dis[idx,-c(1,idx+1)]   
  x <- as.vector(as.matrix(x))  
  x <- x[!is.na(x)]   
  between<-c(between,x) 
}
df_family_str <- data.frame(data='ASTRAL95-superfamily a.29.3',type='SPE',
                            gr=rep(c('within','between'),
                                   c(length(within),length(between))),
                            distance=c(within,between)) 
# ****** sequence95
df <- readRDS("Data/rds/E210.seq_astral_95.rds") 
df = df[!is.na(df$FL),] 
idx<- df$superfamily%in% 'a.29.3'
dis <- as.matrix(dist(df[idx,-c(1:8)],method = manhat))
dis <- data.frame(gr=df$family[idx], dis)
fa<-unique(dis$gr)

between<-c() 
within<-c()
for (i in 1:length(fa)) {  
  print(i)   
  x <- fa[i]  
  idx <- which(dis$gr==x)
  y <- dis[idx,(idx+1)]
  within <- c(within, y[lower.tri(y)])
  x <- dis[idx,-c(1,idx+1)]   
  x <- as.vector(as.matrix(x))  
  x <- x[!is.na(x)]   
  between<-c(between,x) 
}
df_family_seq <- data.frame(data='ASTRAL95-superfamily a.29.3',type='CPE',
                            gr=rep(c('within','between'),
                                   c(length(within),length(between))),
                            distance=c(within,between)) 
# **********
df_family <- rbind(df_family_seq, df_family_str)

FF <- ggboxplot(df_family, x='gr',y='distance', 
          fill = 'gr',alpha=.5,outlier.shape = NA)+
  stat_summary(fun.y=mean, geom="point", shape=8,
               size=2, color="red", fill="red")+xlab('')+
  mytheme()+
  theme(legend.position = 'none',
    axis.text.x = element_blank())+
  scale_fill_viridis(discrete = TRUE, alpha=0.6)+
  stat_compare_means(method = 't.test',size=3,
                     label.y = 18,
                     label.x = 1.4,
                     aes(label = paste0("p = ", ..p.format..)))+
  facet_nested(~ data + type)+
  coord_cartesian(ylim = c(0, 20))
# ********
E<-ggarrange(
  NULL,E, ncol = 1,
  heights = c(0.07, 1),
  labels = c('', "E"),
  font.label = list(size = 30), # color = "red"
  hjust = -.5,vjust = 0
)
FF<-ggarrange(
  NULL,FF, ncol = 1,
  heights = c(0.07, 1),
  labels = c('', "F"),
  font.label = list(size = 30), # color = "red"
  hjust = -.5,vjust = 0
)
EF<-ggarrange(
    E, NULL,FF, nrow = 1,
    widths = c(1, 0.3, 1),
    labels = c("", "", "")
    )

```

## Fig5CD

```{r}
# ******** a.29
# ****** structure40
df <- readRDS("Data/rds/E210.astral40.rds") 
df = df[!is.na(df$FL),] 
idx<- df$fold%in% 'a.29'
dis <- as.matrix(dist(df[idx,-c(1:8)],method = manhat))
dis <- data.frame(gr=df$superfamily[idx], dis)
sf<-unique(dis$gr)

between<-c() 
within<-c()
for (i in 1:length(sf)) {  
  print(i)   
  x <- sf[i]  
  idx <- which(dis$gr==x)
  y <- dis[idx,(idx+1)]
  within <- c(within, y[lower.tri(y)])
  x <- dis[idx,-c(1,idx+1)]   
  x <- as.vector(as.matrix(x))  
  x <- x[!is.na(x)]   
  between<-c(between,x) 
}
df_superfamily_str <- data.frame(data='ASTRAL40-fold a.29',type='SPE',
                            gr=rep(c('within','between'),
                                   c(length(within),length(between))),
                            distance=c(within,between)) 
# ****** sequence40
df <- readRDS("Data/rds/E210.seq_astral40.rds") 
df = df[!is.na(df$FL),] 
idx<- df$fold%in% 'a.29'
dis <- as.matrix(dist(df[idx,-c(1:8)],method = manhat))
dis <- data.frame(gr=df$superfamily[idx], dis)
sf<-unique(dis$gr)

between<-c() 
within<-c()
for (i in 1:length(sf)) {  
  print(i)   
  x <- sf[i]  
  idx <- which(dis$gr==x)
  y <- dis[idx,(idx+1)]
  within <- c(within, y[lower.tri(y)])
  x <- dis[idx,-c(1,idx+1)]   
  x <- as.vector(as.matrix(x))  
  x <- x[!is.na(x)]   
  between<-c(between,x) 
}
df_superfamily_seq <- data.frame(data='ASTRAL40-fold a.29',type='CPE',
                            gr=rep(c('within','between'),
                                   c(length(within),length(between))),
                            distance=c(within,between)) 
# **********
df_superfamily <- rbind(df_superfamily_seq, df_superfamily_str)

C <- ggboxplot(df_superfamily, x='gr',y='distance', 
          fill = 'gr',alpha=.5,outlier.shape = NA)+
  stat_summary(fun.y=mean, geom="point", shape=8,
               size=2, color="red", fill="red")+xlab('')+
  mytheme()+
  theme(legend.position = 'none',
        axis.text.x = element_blank())+
  scale_fill_viridis(discrete = TRUE, alpha=0.6)+
  stat_compare_means(comparisons = my_comparisons, method = 't.test',
                     size=3,label.y = 17,
                     label.x = 1.4,bracket.size = NA,tip.length = NA)+
  facet_nested(~ data + type)+
  coord_cartesian(ylim = c(0, 20))
# ******************************************
# ****** structure95
df <- readRDS("Data/rds/E210.astral_95.rds") 
df = df[!is.na(df$FL),] 
idx<- df$fold%in% 'a.29'
dis <- as.matrix(dist(df[idx,-c(1:8)],method = manhat))
dis <- data.frame(gr=df$superfamily[idx], dis)
sf<-unique(dis$gr)

between<-c() 
within<-c()
for (i in 1:length(sf)) {  
  print(i)   
  x <- sf[i]  
  idx <- which(dis$gr==x)
  y <- dis[idx,(idx+1)]
  within <- c(within, y[lower.tri(y)])
  x <- dis[idx,-c(1,idx+1)]   
  x <- as.vector(as.matrix(x))  
  x <- x[!is.na(x)]   
  between<-c(between,x) 
}
df_superfamily_str <- data.frame(data='ASTRAL95-fold a.29',type='SPE',
                            gr=rep(c('within','between'),
                                   c(length(within),length(between))),
                            distance=c(within,between)) 
# ****** sequence95
df <- readRDS("Data/rds/E210.seq_astral_95.rds") 
df = df[!is.na(df$FL),] 
idx<- df$fold%in% 'a.29'
dis <- as.matrix(dist(df[idx,-c(1:8)],method = manhat))
dis <- data.frame(gr=df$superfamily[idx], dis)
sf <- unique(dis$gr)

between<-c() 
within<-c()
for (i in 1:length(sf)) {  
  print(i)   
  x <- sf[i]  
  idx <- which(dis$gr==x)
  y <- dis[idx,(idx+1)]
  within <- c(within, y[lower.tri(y)])
  x <- dis[idx,-c(1,idx+1)]   
  x <- as.vector(as.matrix(x))  
  x <- x[!is.na(x)]   
  between<-c(between,x) 
}
df_superfamily_seq <- data.frame(data='ASTRAL95-fold a.29',type='CPE',
                            gr=rep(c('within','between'),
                                   c(length(within),length(between))),
                            distance=c(within,between)) 
# **********
df_superfamily <- rbind(df_superfamily_seq, df_superfamily_str)

D <- ggboxplot(df_superfamily, x='gr',y='distance', 
          fill = 'gr',alpha=.5,outlier.shape = NA)+
  stat_summary(fun.y=mean, geom="point", shape=8,
               size=2, color="red", fill="red")+xlab('')+
  mytheme()+
  theme(legend.position = 'none',
        axis.text.x = element_blank())+
  scale_fill_viridis(discrete = TRUE, alpha=0.6)+
  stat_compare_means(comparisons = my_comparisons, method = 't.test',size=3,
                     label.x = 1.4,label.y = 17,bracket.size = NA,tip.length = NA)+
  facet_nested(~ data + type)+
  coord_cartesian(ylim = c(0, 20))
# ********
C<-ggarrange(
  NULL,C, ncol = 1,
  heights = c(0.07, 1),
  labels = c('', "C"),
  font.label = list(size = 30), # color = "red"
  hjust = -.5,vjust = 0
)
D<-ggarrange(
  NULL,D, ncol = 1,
  heights = c(0.07, 1),
  labels = c('', "D"),
  font.label = list(size = 30), # color = "red"
  hjust = -.5,vjust = 0
)
CD<-ggarrange(
    C, NULL,D, nrow = 1,
    widths = c(1, 0.3, 1),
    labels = c("", "", "")
    )
```

## Fig5AB

```{r}
my_comparisons<-list(c('within','between'))
# ******** a
# ****** structure40
df <- readRDS("Data/rds/E210.astral40.rds") 
df = df[!is.na(df$FL),] 
idx<- df$class%in% 'a'
dis <- as.matrix(dist(df[idx,-c(1:8)],method = manhat))
dis <- data.frame(gr=df$fold[idx], dis)
fo<-unique(dis$gr)

between<-c() 
within<-c()
for (i in 1:length(fo)) {  
  print(i)   
  x <- fo[i]  
  idx <- which(dis$gr==x)
  y <- dis[idx,(idx+1)]
  within <- c(within, y[lower.tri(y)])
  x <- dis[idx,-c(1,idx+1)]   
  x <- as.vector(as.matrix(x))  
  x <- x[!is.na(x)]   
  between<-c(between,x) 
}
wit <- within[sample(length(within),1000)] 
bet <- between[sample(length(between),1000)] 
df_fold_str <- data.frame(data='ASTRAL40-class alpha',type='SPE',
                            gr=rep(c('within','between'),c(1000,1000)),
                            distance=c(wit,bet)) 
# ****** sequence40
df <- readRDS("Data/rds/E210.seq_astral40.rds") 
df = df[!is.na(df$FL),] 
idx<- df$class%in% 'a'
dis <- as.matrix(dist(df[idx,-c(1:8)],method = manhat))
dis <- data.frame(gr=df$fold[idx], dis)
fo <- unique(dis$gr)

between<-c() 
within<-c()
for (i in 1:length(fo)) {  
  print(i)   
  x <- fo[i]  
  idx <- which(dis$gr==x)
  y <- dis[idx,(idx+1)]
  within <- c(within, y[lower.tri(y)])
  x <- dis[idx,-c(1,idx+1)]   
  x <- as.vector(as.matrix(x))  
  x <- x[!is.na(x)]   
  between<-c(between,x) 
}
wit <- within[sample(length(within),1000)] 
bet <- between[sample(length(between),1000)] 
df_fold_seq <- data.frame(data='ASTRAL40-class alpha',type='CPE',
                            gr=rep(c('within','between'),c(1000,1000)),
                            distance=c(wit,bet))
# **********
df_fold <- rbind(df_fold_seq, df_fold_str)

A <- ggboxplot(df_fold, x='gr',y='distance', 
          fill = 'gr',alpha=.5,outlier.shape = NA)+
  stat_summary(fun.y=mean, geom="point", shape=8,
               size=2, color="red", fill="red")+xlab('')+
  mytheme()+
  theme(legend.position = 'none',
        axis.text.x = element_blank())+
  scale_fill_viridis(discrete = TRUE, alpha=0.6)+
  stat_compare_means(comparisons = my_comparisons, method = 't.test',size=3,
                     label.y = 30,bracket.size = NA,tip.length = NA)+
  facet_nested(~ data + type)+
  coord_cartesian(ylim = c(0, 40))
# ******************************************
# ****** structure95
df <- readRDS("Data/rds/E210.astral_95.rds") 
df = df[!is.na(df$FL),] 
idx<- df$class%in% 'a'
dis <- as.matrix(dist(df[idx,-c(1:8)],method = manhat))
dis <- data.frame(gr=df$fold[idx], dis)
fo<-unique(dis$gr)

between<-c() 
within<-c()
for (i in 1:length(fo)) {  
  print(i)   
  x <- fo[i]  
  idx <- which(dis$gr==x)
  y <- dis[idx,(idx+1)]
  within <- c(within, y[lower.tri(y)])
  x <- dis[idx,-c(1,idx+1)]   
  x <- as.vector(as.matrix(x))  
  x <- x[!is.na(x)]   
  between<-c(between,x) 
}
wit <- within[sample(length(within),1000)]
bet <- between[sample(length(between),1000)] 
df_fold_str <- data.frame(data='ASTRAL95-class alpha',type='SPE',
                            gr=rep(c('within','between'),c(1000,1000)),
                            distance=c(wit,bet))
# ****** sequence95
df <- readRDS("Data/rds/E210.seq_astral_95.rds") 
df = df[!is.na(df$FL),] 
idx<- df$class%in% 'a'
dis <- as.matrix(dist(df[idx,-c(1:8)],method = manhat))
dis <- data.frame(gr=df$fold[idx], dis)
fo<-unique(dis$gr)

between<-c() 
within<-c()
for (i in 1:length(fo)) {  
  print(i)   
  x <- fo[i]  
  idx <- which(dis$gr==x)
  y <- dis[idx,(idx+1)]
  within <- c(within, y[lower.tri(y)])
  x <- dis[idx,-c(1,idx+1)]   
  x <- as.vector(as.matrix(x))  
  x <- x[!is.na(x)]   
  between<-c(between,x) 
}
wit <- within[sample(length(within),1000)] 
bet <- between[sample(length(between),1000)] 
df_fold_seq <- data.frame(data='ASTRAL95-class alpha',type='CPE',
                            gr=rep(c('within','between'),c(1000,1000)),
                            distance=c(wit,bet)) 
# **********
df_fold <- rbind(df_fold_seq, df_fold_str)

B <- ggboxplot(df_fold, x='gr',y='distance', 
          fill = 'gr',alpha=.5,outlier.shape = NA)+
  stat_summary(fun.y=mean, geom="point", shape=8,
               size=2, color="red", fill="red")+xlab('')+
  mytheme()+
  theme(legend.position = 'none',
        axis.text.x = element_blank())+
  scale_fill_viridis(discrete = TRUE, alpha=0.6)+
  stat_compare_means(comparisons = my_comparisons, method = 't.test',size=3,
                     label.y = 30, bracket.size = NA,tip.length = NA)+
  facet_nested(~ data + type)+
  coord_cartesian(ylim = c(0, 40))
# ********
A<-ggarrange(
  NULL,A, ncol = 1,
  heights = c(0.07, 1),
  labels = c('', "A"),
  font.label = list(size = 30), # color = "red"
  hjust = -.5,vjust = 0
)
B<-ggarrange(
  NULL,B, ncol = 1,
  heights = c(0.07, 1),
  labels = c('', "B"),
  font.label = list(size = 30), # color = "red"
  hjust = -.5,vjust = 0
)
AB<-ggarrange(
    A, NULL,B, nrow = 1,
    widths = c(1, 0.3, 1),
    labels = c("", "", "")
    )
```

##Fig5All

```{r}
f5all <- ggarrange(NULL,AB,CD,EF,ncol = 1,
          heights = c(0.1,1,1,1))
cowplot::plot_grid(f5all, mylegend, ncol = 1, rel_heights = c(1,.03))
# save pdf 10x9
```

## Fig6 ferritin

```{r}
E210_ferritin <- readRDS("Data/rds/E210_ferritin.rds")
df <- E210_ferritin
sc <- apply(df[,-c(1:3)], 2, FUN = function(x){x/sd(x)})
df[,-c(1:3)] <- sc
dis <- proxy::dist(df[,-c(1:3)], method = manhat)

nnet <- neighborNet(dis)
ggsplitnet(nnet) + geom_tiplab2(aes(label=label),
                                hjust=-.1,size=5,
                                color='blue')+
  ggexpand(.1) + ggexpand(.1, direction=-1)
# write.nexus.networx(nnet,'Data/rds/E210_ferritin_manhat.nxs')
# --------------------------------------------------------------------
# ----   the 'E210_ferritin_manhat.nxs' file 
# -----      was load on SplitsTree4(v 4.19.2) to visualize
# --------------------------------------------------------------------
```

## Fig7 covid

```{r}
# --------------- CPE -----------------
E210.seq_spike <- readRDS("Data/rds/E210.seq_spike_close.rds")
df <- E210.seq_spike
for (i in 1:nrow(df)) {
  print(i)
  df[i,-c(1:5)]<-df[i,-c(1:5)]*aij210
}

rownames(df) = df$pdbID
x <- df[,-c(1:5)]/df$length
x  <- as.matrix(x) 
hc <- x %>% proxy::dist(method = manhat)
hc <- hc%>% hclust(method = "ward.D2")
adjustedRandIndex(cutree(hc, 3), df$virus)
classError(cutree(hc, 3), df$virus)
dend <- hc %>% as.dendrogram

df <- df[with(df, order(df$virus)), ]
row.names(df) <- df$pdbID
rn <- df$pdbID
tree_data <- as.phylo(dend)
grp <- list(MERS_Cov     = rn[1:32],
            SARS_Cov  = rn[33:63],
            SARS_Cov2  = rn[64:143])

p_data <- ggtree(tree_data, layout = 'dendrogram',
                 size = 1) 

t_CPE = groupOTU(p_data, grp, "groups") + aes(color=groups) +
  theme(legend.position="none",
        plot.title = element_text(size = 20, face="bold",hjust = 0.5,vjust = -3))+
#  geom_tiplab2(aes(label=label,angle=angle),
#               hjust=-.1,size=1.5,fontface="bold",align=F)+
  geom_tiplab(aes(label=label),
               hjust=1,size=1.5,fontface="bold",align=F)+
  scale_color_discrete(breaks=c('MERS_Cov', 'SARS_Cov', 'SARS_Cov2'),
                      type =  c('black',"blue","green","red" ))+
  ggtitle('CPE')
# -----------------------------------------------------
# ------------ SPE ----------------
E210_spike <- readRDS("Data/rds/E210_spike_close.rds")
df <- E210_spike

rownames(df) = df$pdbID
x <- df[,-c(1:5)]/df$length
x  <- as.matrix(x) 
hc <- x %>% proxy::dist(method = manhat)
hc <- hc%>% hclust(method = "ward.D2")
adjustedRandIndex(cutree(hc, 3), df$virus)
classError(cutree(hc, 3), df$virus)
dend <- hc %>% as.dendrogram

df <- df[with(df, order(df$virus)), ]
row.names(df) <- df$pdbID
rn <- df$pdbID

tree_data <- as.phylo(dend)
grp <- list(MERS_Cov     = rn[1:32],
            SARS_Cov  = rn[33:63],
            SARS_Cov2  = rn[64:143])

p_data <- ggtree(tree_data, layout = 'dendrogram',
                 #branch.length='none',
                 size = 1) 

t_SPE = groupOTU(p_data, grp, "groups") + aes(color=groups) +
  theme(legend.position="none",
        plot.title = element_text(size = 20, face="bold",hjust = 0.5,vjust = -3))+
  geom_tiplab(aes(label=label),
               hjust=1,size=1.5,fontface="bold",align=F)+
  scale_color_discrete(breaks=c('MERS_Cov', 'SARS_Cov', 'SARS_Cov2'),
                      type =  c('black',"blue","green","red"  ))+
  ggtitle('SPE')
# -----------------------------------------------
# ------------- RMSD --------------
df <- E210.seq_spike
rms <- data.frame(readRDS('Data/covidPDB/RMSD.rds'))
diag(rms)<-0

hc <- as.dist(rms)
hc <- hc%>% hclust(method = "ward.D2")

adjustedRandIndex(cutree(hc, 3), df$virus)
classError(cutree(hc, 3), df$virus)


df <- df[with(df, order(df$virus)), ]
rn <- df$pdbID
tree_data <- as.phylo(hc)
grp <- list(MERS_Cov  = rn[1:32],
            SARS_Cov  = rn[33:63],
            SARS_Cov2 = rn[64:143])

p_data <- ggtree(tree_data, layout = 'dendrogram',
                 size = 1) 

t_RMSS <- groupOTU(p_data, grp, "groups") + aes(color=groups) +
       theme(legend.position="none",
             plot.title = element_text(size = 20, face="bold",hjust = 0.5,vjust = -3))+
       geom_tiplab(aes(label=label),
                    hjust=1,size=1.5,fontface="bold",align=F)+
       scale_color_discrete(breaks=c('MERS_Cov', 'SARS_Cov', 'SARS_Cov2'),
                            type =  c("blue","green","red" ))+
  ggtitle('RMSD')
# --------------------------------------------
# ----------- TM-Vec -----------------
df <- E210.seq_spike
tm_vec <- read.csv('Data/covidPDB/disTM_vec.csv')
colnames(tm_vec) <- rownames(tm_vec) <- df$pdbID
tm_vec <- 1 - tm_vec

hc <- as.dist(tm_vec)
hc <- hc%>% hclust(method = "ward.D2")

adjustedRandIndex(cutree(hc, 3), df$virus)
classError(cutree(hc, 3), df$virus)
dend <- hc %>% as.dendrogram

df <- df[with(df, order(df$virus,decreasing = T)), ]
rn <- df$pdbID
tree_data <- as.phylo(dend)
grp <- list(MERS_Cov  = rn[112:143],
            SARS_Cov  = rn[81:111],
            SARS_Cov2 = rn[1:80])

p_data <- ggtree(tree_data, layout = 'dendrogram',
                 size = 1) 
# ggtree(tr) + geom_text(aes(label=node))
p_data <- flip(p_data, 152, 151)

t_tmVec <- groupOTU(p_data, grp, "groups") + aes(color=groups) +
       theme(legend.position="none",
             plot.title = element_text(size = 20, face = 'bold',hjust = 0.5,vjust = -3))+
       geom_tiplab(aes(label=label),
                    hjust=1,size=1.5,fontface="bold",align=F)+
       scale_color_discrete(breaks=c('MERS_Cov', 'SARS_Cov', 'SARS_Cov2'),
                            type =  c("blue","green","red" ))+
  ggtitle('TM-Vec')
# --------------------------------------
mylegend <- get_legend(t_SPE+
                       theme(legend.position = 'bottom',
                             legend.title = element_blank(),
                             legend.text = element_text(size = 20)))


AB<-ggarrange(NULL,NULL,
    t_CPE,t_SPE, NULL,NULL,
    t_RMSS,t_tmVec,
    ncol = 2,nrow = 4,
    heights = c(.15, 1, .3, 1),
    widths = c(1,1),
    labels = c('',"", "A", "B",'','','C','D'),
    font.label = list(size = 55), # color = "red"
    hjust = 0,vjust = .5
    )

cowplot::plot_grid(AB, mylegend, ncol = 1, rel_heights = c(1,.1))
# save FIG6.pdf 20x10
```

## Fig8 Bacteriocin Tm-Vec

```{r}
source('mytheme.R')
tm <- readRDS('Data/rds/bacteriocin_tm_vec.rds')
tm2 <- tm[!is.na(tm$status2),-24]
colnames(tm2)[24]<-'status'
tm2 <- rbind(tm[,-25],tm2)

tm2 <- tm2[,c(5,20,21,6,23,24)] # 22~6 DeepBlast
colnames(tm2)[-6] <- c('Alphafold2','Omegafold','ESMfold','TM_vec','CPE')
tm2 <- melt(tm2,variable.name = 'method',value.name = 'score')
tm2$method <- factor(tm2$method,levels = c('TM_vec','Alphafold2','Omegafold','ESMfold','CPE'))
p1<-ggplot(tm2, aes(status,score,fill=method))+
  geom_boxplot(outlier.shape = NA,
               color='black',
               size=rep(c(rep(.2,4),1),3),
               alpha=rep(c(rep(.5,4),1),3),
               width=.4
               )+
  coord_cartesian(ylim = c(0.1, 1))+
  xlab('')+
    geom_hline(yintercept = .5, linetype="dashed", 
             color = "red", size=.7)+
  mytheme()+
  theme(legend.title = element_blank(),
        axis.text.y = element_text(size=13),
        axis.text.x = element_text(color = 'black',size = 15, face = 'bold'),
        axis.title.y = element_text(size = 20,vjust = 2, face = 'bold'),
        legend.text = element_text(size = 15))+
  scale_fill_discrete(labels=c('TM_vec','Alphafold2',
                               'Omegafold','ESMfold',
                               expression(bold("CPE"))))

# --------------------------------
# -----  UMAP
df <- readRDS('Data/rds/E210.seq_bacteriocin.rds')
dis <- as.matrix(proxy::dist(df[,-c(1:6)], method = manhat))
ump <- umap(d = dis,
            n_neighbors = 100,
            min_dist = 0.1,
            input="dist")

ump_df <- data.frame(class=df$class,
                     UMAP1 = ump$layout[, 1],
                     UMAP2 = ump$layout[, 2])

p2<-ggplot(ump_df,
       aes(UMAP1, UMAP2, color= class)) +
  geom_point(alpha=.7, size=2) + 
  mytheme()+
  theme(legend.title = element_blank(),
        legend.position = 'bottom',
        axis.title = element_text(size = 15),
        axis.title.y = element_text(size = 15,vjust = 5),
        legend.text = element_text(size = 15))+
  scale_color_manual(values = c('green','magenta','blue'))


p1 <- ggarrange(NULL,NULL,
          NULL,p1,ncol = 2,nrow = 2,
          labels = c('','B'),
          heights = c(0.1,1),
          widths = c(.1,1),
          font.label = list(size = 50),
          hjust = 0,vjust = 1.2)
p2 <- ggarrange(NULL,NULL,
          NULL,p2,ncol = 2,nrow = 2,
          labels = c('','A'),
          heights = c(0.1,1),
          widths = c(.1,1),
          font.label = list(size = 50),
          hjust = .5,vjust = 1.2)

ggarrange(p2,NULL,p1,ncol = 3,nrow = 1,
          widths = c(.5,.05,1))
# save FIG8.pdf 15x8
```

##Fig9 DrugTarget

```{r}
source('mytheme.R')
my_sab <- readRDS('Data/rds/my_sab.rds')
my_sab <- as.data.frame(as.table(my_sab)) 
colnames(my_sab) <- c("d1", "d2", "my_sAB") 
my_sab <- my_sab[!is.na(my_sab$my_sAB), ]
sab <- readRDS('Data/rds/sAB.rds')
colnames(sab)[1:2] <- c('d1','d2')

df <- left_join(sab,my_sab,c('d1','d2'))
ggplot(df,aes(sAB,my_sAB))+
  geom_point(alpha=.5)+geom_smooth(method = 'lm')+
  stat_cor(col='red',size=8)+mytheme()+
    theme(axis.title = element_text(size=20),
        axis.text.x = element_text(size = 13),
        axis.text.y = element_text(size = 13),)+
  xlab('sAB (PPI)')+ylab('sAB (CPE)')
# save FIG9.pdf 10x7
```

# Tables
## Table1 FiveSF

```{r}
# -------- 5 sf
win <- 'a.4.5'
imu <- 'b.1.1'
ph <- 'b.55.1'
ub <- 'd.15.1'
ntf <- 'd.17.4'

fiveSF <- c(win,imu,ph,ub,ntf)
#############
df5 <- readRDS('Data/rds/E210.seq_df5.rds')
df5 <- df5[!is.na(df5$FF),]
###############
dis <- as.matrix(dist(df5[,-c(1:8)],method = manhat))
diag(dis) <- NA

im <- apply(dis,1, FUN = which.min)
res <- data.frame(source=df5$superfamily, target=df5$superfamily[im])
cm <- matrix(0,5,5)
colnames(cm) <- rownames(cm) <- fiveSF
for (sf in fiveSF) {
  x <- res[res$source%in%sf,]
  z <- table(x$target)
  cm[sf,names(z)]<-z
}
Accuracy<-sum(diag(cm))/sum(cm)
Precision <- diag(cm)/colSums(cm)
Recall <- diag(cm)/rowSums(cm)
F1 <- (2 * Precision * Recall) /(Precision + Recall)

res1nn<-data.frame(t(round(c(Accuracy,F1),2)))
# ------------------------------------
df5$superfamily <- factor(df5$superfamily)
kfolds <- createFolds(df5$superfamily, k = 10)
res<-c()
for (i in 1:10) {
  print(i)
  x <- kfolds[[i]]
  tr <- df5[-x,c(7,9:218)]
  te <- df5[x,c(7,9:218)]
  rf = randomForest(superfamily~.,data = tr)
  p2 <- predict(rf, te)
  cm2 <- confusionMatrix(p2, te$superfamily)
  Accuracy <- c(cm2$overall['Accuracy'], F1=cm2$byClass[,'F1'])
  res<-rbind(res,Accuracy)
}
res <- rbind(res,colMeans(res))
res <- round(res,2)
rownames(res) <- c(paste0("Fold_",1:length(kfolds)),'Average')
colnames(res)[-1] <- gsub('.Class','',colnames(res)[-1])
# -----------------
tab1 <- rbind(res1nn,res[11,])
colnames(tab1)<-colnames(res)
tab1 <- data.frame(method=c('1NN','RF'),tab1)
```

## Table2 CT_Ho

```{r}
# -------------------- 1NN 
df <- readRDS('Data/rds/E210.seq_CT_Ho.rds')
df <- df[!is.na(df$FF),]
twoSF <- unique(df$cathID)

#dis <- read.csv('Data/csv/disTM_vec_CTHo.csv')
dis <- as.matrix(dist(df[,-c(1:9)], method = manhat))
diag(dis) <- NA

im <- apply(dis,1, FUN = which.min)
res <- data.frame(source=df$cathID, target=df$cathID[im])
## ----------
cm <- matrix(0,2,2)
colnames(cm) <- rownames(cm) <- twoSF
for (sf in twoSF) {
  x <- res[res$source%in%sf,]
  z <- table(x$target)
  cm[sf,names(z)]<-z
}
round(sum(diag(cm))/sum(cm),2)
```
